FROM debian:testing-slim

RUN apt-get update && apt-get install -y autoconf automake gcc clang \
  libtool libtool-bin make pkg-config libcunit1-dev libssl-dev \
  exuberant-ctags git
RUN apt-get clean
