CONTIKI_PROJECT = server
all: $(CONTIKI_PROJECT)

CONTIKI = ../../../..

ifneq ($(NODE_ADDR),)
	CFLAGS += -DNODE_ADDR=$(NODE_ADDR)
endif

MODULES += os/net/app-layer/libcoap

include $(CONTIKI)/Makefile.include
